# Generated by Django 5.2 on 2025-08-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examattempt',
            old_name='total_score',
            new_name='obtained_score',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='answers',
        ),
        migrations.AddField(
            model_name='examattempt',
            name='question_attempts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
